name: ContinuosIntegration

on:
  
  push:
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3

      - name: Build and Check code coverage
        run: |
          chmod +x gradlew
          ./gradlew clean build jacocoTestCoverageVerification
          build_output=$(ls -t build/libs/*.jar | head -n 1)
          echo "Built artifact: $build_output"
          ls -ltr
          
      - name: SonarCloud Analysis
        run: |
          chmod +x gradlew
          ./gradlew jacocoTestReport sonar -Dsonar.token=${{ secrets.TOKEN_SONARCLOUD }} --info --stacktrace
          #./gradlew build sonar -Dsonar.token=${{ secrets.TOKEN_SONARCLOUD }}

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.TOKEN_SONARCLOUD }} 
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          scanMetadataReportFile: build/sonar/report-task.txt   

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copia de Jar a Raiz de proyecto
        run: |
          cp $GITHUB_WORKSPACE/build/libs/*.jar .
          chmod 777 *.jar
          ls -lt 

      - name: Docker Build
        run: |
          docker build --tag josezumba/microservicio-java:latest .
          docker images

      - name: Docker Push
        run: |
          docker push josezumba/microservicio-java


  deploy:
    runs-on: self-hosted
    needs: build
    steps:

      - uses: actions/checkout@v3
    
      - name: Deploy a Minikube
        run: |
          kubectl apply -f deployment.yml

  Jmeter:
    runs-on: self-hosted
    needs: deploy
    steps:
      - uses: actions/checkout@v3

      - name: Download jMeter
        run: |
          Invoke-WebRequest -Uri https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.2.tgz -OutFile apache-jmeter-5.6.2.tgz
          tar -xvzf apache-jmeter-5.6.2.tgz
          ls
          
      - name: Ejecutar prueba con jmeter
        run: |
          Get-Location
          .\apache-jmeter-5.6.2\bin\jmeter.bat -n -t rendimiento\prueba_microservicio.jmx -l rendimiento\prueba_respuesta.jtl

      - name: Check ejecución
        run: |
          Get-ChildItem Env:
          .\apache-jmeter-5.6.2\bin\jmeter.bat -n -t rendimiento\prueba_microservicio.jmx -l rendimiento\prueba_respuesta.jtl
